remote_theme: pages-themes/architect@v0.2.0

title: Claire’s Delight
description: Claire’s Delight is a comprehensive product-based platform designed to showcase and sell a wide range of high-quality spices for cooking and medicinal purposes. 
