/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/r2NhijMefaC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { EyeIcon } from "lucide-react"

export function SettingsTab() {
  return (
    <Card className="w-full max-w-4xl">
      <CardHeader>
        <CardTitle>Settings</CardTitle>
        <CardDescription>Manage your account and preferences.</CardDescription>
      </CardHeader>
      <Tabs defaultValue="account" className="w-full">
        <TabsList className="border-b">
          <TabsTrigger value="account">Account</TabsTrigger>
          <TabsTrigger value="groups">Groups</TabsTrigger>
          <TabsTrigger value="security">Security</TabsTrigger>
        </TabsList>
        <TabsContent value="account">
          <CardContent className="grid gap-8">
            <div className="grid gap-6">
              <div className="grid grid-cols-[150px_1fr] items-center gap-4">
                <Label htmlFor="name">Name</Label>
                <Input id="name" defaultValue="John Doe" />
              </div>
              <div className="grid grid-cols-[150px_1fr] items-center gap-4">
                <Label htmlFor="email">Email</Label>
                <Input id="email" defaultValue="john@example.com" />
              </div>
              <div className="grid grid-cols-[150px_1fr] items-center gap-4">
                <Label htmlFor="password">Password</Label>
                <div className="flex items-center gap-2">
                  <Input id="password" type="password" defaultValue="********" />
                  <Button variant="ghost" size="icon">
                    <EyeIcon className="h-5 w-5" />
                  </Button>
                </div>
              </div>
              <div className="grid grid-cols-[150px_1fr] items-center gap-4">
                <Label htmlFor="username">Username</Label>
                <Input id="username" defaultValue="johndoe" />
              </div>
              <div className="grid grid-cols-[150px_1fr] items-center gap-4">
                <Label htmlFor="timezone">Timezone</Label>
                <Select>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select timezone" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="utc">UTC</SelectItem>
                    <SelectItem value="est">EST</SelectItem>
                    <SelectItem value="pst">PST</SelectItem>
                    <SelectItem value="cet">CET</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid grid-cols-[150px_1fr] items-center gap-4">
                <Label htmlFor="language">Language</Label>
                <Select>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select language" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="en">English</SelectItem>
                    <SelectItem value="es">Español</SelectItem>
                    <SelectItem value="fr">Français</SelectItem>
                    <SelectItem value="de">Deutsch</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </CardContent>
        </TabsContent>
        <TabsContent value="groups">
          <CardContent className="grid gap-8">
            <div className="grid gap-6">
              <div className="grid grid-cols-[150px_1fr] items-center gap-4">
                <Label htmlFor="groups">Groups</Label>
                <Select>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select groups" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="manager">Manager</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid grid-cols-[150px_1fr] items-center gap-4">
                <Label htmlFor="group-permissions">Group Permissions</Label>
                <div className="flex flex-col gap-2">
                  <div className="flex items-center gap-2">
                    <Checkbox id="read" />
                    <Label htmlFor="read">Read</Label>
                  </div>
                  <div className="flex items-center gap-2">
                    <Checkbox id="write" />
                    <Label htmlFor="write">Write</Label>
                  </div>
                  <div className="flex items-center gap-2">
                    <Checkbox id="admin" />
                    <Label htmlFor="admin">Admin</Label>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </TabsContent>
        <TabsContent value="security">
          <CardContent className="grid gap-8">
            <div className="grid gap-6">
              <div className="grid grid-cols-[150px_1fr] items-center gap-4">
                <Label htmlFor="security">Security</Label>
                <div className="flex flex-col gap-2">
                  <div className="flex items-center gap-2">
                    <Checkbox id="2fa" />
                    <Label htmlFor="2fa">Enable Two-Factor Authentication</Label>
                  </div>
                  <div className="flex items-center gap-2">
                    <Checkbox id="logout" />
                    <Label htmlFor="logout">Automatically log out after 30 minutes of inactivity</Label>
                  </div>
                </div>
              </div>
              <div className="grid grid-cols-[150px_1fr] items-center gap-4">
                <Label htmlFor="security-route">Security Route</Label>
                <div className="flex flex-col gap-2">
                  <div className="flex items-center gap-2">
                    <Checkbox id="secure-route-1" />
                    <Label htmlFor="secure-route-1">Secure Route 1</Label>
                  </div>
                  <div className="flex items-center gap-2">
                    <Checkbox id="secure-route-2" />
                    <Label htmlFor="secure-route-2">Secure Route 2</Label>
                  </div>
                  <div className="flex items-center gap-2">
                    <Checkbox id="secure-route-3" />
                    <Label htmlFor="secure-route-3">Secure Route 3</Label>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </TabsContent>
      </Tabs>
      <CardFooter className="flex justify-end gap-2">
        <Button variant="outline">Cancel</Button>
        <Button>Save Changes</Button>
      </CardFooter>
    </Card>
  )
}