name: Claires CI/CD

on:
  push:
    branches:
      - main
      - testing
      - development
      - staging
      - 'feature/**'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        
    - run: npm ci
    - run: npm run build
    - run: npm run export
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: ./out

  deploy-to-production:
    needs: build
    
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist-files
        
    # Deploy to production server
        
  deploy-to-testing:
    needs: build
    
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/testing'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist-files
        
    # Deploy to testing environment
        
  deploy-to-development:
    needs: build
    
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/development'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist-files
        
    # Deploy to development environment
        
  deploy-to-staging:
    needs: build
    
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/staging'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist-files
        
    # Deploy to staging environment
        
  deploy-to-review:
    needs: build
    
    runs-on: ubuntu-latest
    
    if: startsWith(github.ref, 'refs/heads/feature/')
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist-files
        
    # Deploy to review environment
