name: Next.js CI

on:
  push:
    branches: [testing]
  pull_request:
    branches: [testing]

jobs:

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: 18
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm run test
      
    - name: Build
      run: npm run build

    - name: Export
      run: npm run export
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: ./out